# Generated by Django 3.2.4 on 2021-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=12, null=True)),
                ('event_date', models.DateField(null=True)),
                ('event_planner', models.CharField(max_length=12, null=True)),
                ('event_duration', models.CharField(max_length=12, null=True)),
                ('event_participant', models.PositiveSmallIntegerField(null=True)),
                ('event_approved_by', models.CharField(max_length=13, null=True)),
                ('event_id', models.CharField(max_length=13, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
    ]
