# Generated by Django 3.2.4 on 2021-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=16)),
                ('course_code', models.CharField(max_length=12)),
                ('course_description', models.CharField(max_length=30)),
                ('course_trainer', models.CharField(max_length=18)),
                ('course_syllabus', models.FileField(upload_to='')),
                ('course_notes', models.FileField(upload_to='')),
                ('course_duration', models.DateTimeField()),
            ],
        ),
    ]
