# Generated by Django 3.2.4 on 2021-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=10)),
                ('event_date', models.DateTimeField()),
                ('event_organizer', models.CharField(max_length=10)),
                ('event_agenda', models.CharField(max_length=14)),
                ('event_duration', models.TimeField()),
                ('event_venue', models.CharField(max_length=14)),
                ('event_attendees_by', models.CharField(max_length=30)),
            ],
        ),
    ]
