# Generated by Django 3.2.4 on 2021-08-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsregistration',
            old_name='event_attendees_by',
            new_name='event_attendees',
        ),
    ]
