# Generated by Django 3.2.4 on 2021-08-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('courses', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='images')),
                ('bank_account', models.CharField(max_length=16)),
                ('resume', models.FileField(upload_to='')),
                ('country', models.CharField(max_length=12)),
                ('salary', models.PositiveBigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
