# Generated by Django 3.2.4 on 2021-09-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=12)),
                ('country', models.CharField(default='Valid', max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('guardian', models.CharField(max_length=18)),
                ('class_name', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=8)),
                ('big_sister', models.CharField(default='Valid', max_length=18)),
                ('mentors_name', models.CharField(max_length=18)),
                ('laptop_number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
